version: "2"
services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    command:
      [
        "bash",
        "scripts/wait-for-it.sh",
        "postgres:${DATABASE_PORT}",
        "--",
        "bash",
        "scripts/start.sh",
      ]
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
